let config=require("../config");class OwnerManager{constructor(){this.ownerSet=new Set,this.mode="public",this.initialized=!1,this.db=null}normalizeJid(e){if(!e)return{full:"",numeric:null,type:"unknown"};let t=String(e);if(t.includes("@lid")){let e=t.split(":")[0],r=(e=e.replace("@lid","")).match(/\d+/g),n=r?r.join(""):e;return{full:t.toLowerCase(),numeric:n,type:"lid"}}e=(t=t.split(":")[0]).match(/(\d+)/);return e?{full:e[1]+"@s.whatsapp.net",numeric:e[1],type:"normal"}:{full:t.toLowerCase(),numeric:null,type:"unknown"}}async initialize(e,r=null,n=null){this.db=e;var t=config.OWNER_NUMBER;if(t&&(t=String(t).replace(/\D/g,""),this.ownerSet.add(t),console.log("👑 Added owner number: "+t),this.ownerSet.add(t=t+"@s.whatsapp.net"),console.log("👑 Added owner JID: "+t)),n&&(t=this.normalizeJid(n),this.ownerSet.add(n),t.numeric&&(this.ownerSet.add(t.numeric),console.log(`👑 Added owner LID numeric: ${t.numeric} (from ${n})`)),console.log("👑 Added owner LID: "+n)),r&&(t=this.normalizeJid(r),this.ownerSet.add(r),t.numeric&&(this.ownerSet.add(t.numeric),console.log(`👑 Added owner JID numeric: ${t.numeric} (from ${r})`)),console.log("👑 Added owner JID: "+r)),n&&(t=n.split(":")[0].replace("@lid",""),this.ownerSet.add(t),console.log("👑 Added raw LID number: "+t)),e)try{var i=await e.getSetting("owners",[]);Array.isArray(i)&&(i.forEach(e=>{var r;e&&((r=this.normalizeJid(e)).numeric&&this.ownerSet.add(r.numeric),r.full&&this.ownerSet.add(r.full),this.ownerSet.add(e))}),console.log(`👑 Added ${i.length} DB owners`)),this.mode=await e.getSetting("mode",config.MODE||"public")}catch(e){console.error("Failed to load owners from DB:",e.message)}return this.initialized=!0,console.log(`👑 Owner system initialized with ${this.ownerSet.size} identifier(s)`),console.log("👑 Owner identifiers: "+Array.from(this.ownerSet).join(", ")),this}isOwner(e){if(e&&this.initialized){if(this.ownerSet.has(e))return console.log("✅ Owner match (direct): "+e),!0;var r=this.normalizeJid(e);if(console.log(`🔍 Owner check: JID=${e}, Numeric=${r.numeric}, Type=`+r.type),r.full&&this.ownerSet.has(r.full))return console.log("✅ Owner match (full JID): "+r.full),!0;if(r.numeric&&this.ownerSet.has(r.numeric))return console.log("✅ Owner match (numeric): "+r.numeric),!0;if("lid"===r.type&&r.numeric)for(var n of this.ownerSet)if(String(n).replace(/\D/g,"")===r.numeric)return console.log("✅ Owner match (LID numeric): "+r.numeric),!0}return!1}getOwnerOnlyMessage(e="this command"){var r=Array.from(this.ownerSet).filter(e=>/^\d+$/.test(e)&&9<e.length).join(", ");return{text:`┏━━━━━━━━━━━━━━━━━━━┓
`+`┃ *${config.BOT_NAME}*
`+`┗━━━━━━━━━━━━━━━━━━━┛

`+`👑 *Owner Only Command*

`+`You must be an owner to use ${e}.

`+`• Current mode: ${this.mode}
`+`• Owners: ${r||"Not set"}

`+"> created by wanga"}}async addOwner(e,r){var n=this.normalizeJid(e);return n.numeric&&this.ownerSet.add(n.numeric),n.full&&this.ownerSet.add(n.full),this.ownerSet.add(e),r&&(n=Array.from(this.ownerSet).filter(e=>e.includes("@")||/^\d+$/.test(e)),await r.setSetting("owners",n)),!0}async removeOwner(e,r){var n=this.normalizeJid(e),t=String(config.OWNER_NUMBER).replace(/\D/g,"");return n.numeric!==t&&(n.numeric&&this.ownerSet.delete(n.numeric),n.full&&this.ownerSet.delete(n.full),this.ownerSet.delete(e),r&&(t=Array.from(this.ownerSet).filter(e=>e.includes("@")||/^\d+$/.test(e)),await r.setSetting("owners",t)),!0)}getMode(){return this.mode}async setMode(e,r){return!!["public","private"].includes(e)&&(this.mode=e,r&&await r.setSetting("mode",e),!0)}getPrimaryOwner(){return String(config.OWNER_NUMBER).replace(/\D/g,"")+"@s.whatsapp.net"}getAllOwners(){return Array.from(this.ownerSet).filter(e=>e.includes("@"))}getOwnerCount(){return this.getAllOwners().length}}module.exports=OwnerManager;